#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Mikael Magnusson

START=15

boot() {
	# Only execute for lxc containers
	if [ "$container" != "lxc" ]; then
		exit 0
	fi
	local has_kmod=$(opkg list-installed | grep kmod | head -1 | cut -d" " -f1)
	if [ ! -e /lib/modules/$(uname -r) ] && [ -n "$has_kmod" ]; then
		local modulesdir=$(basename $(dirname $(opkg files "$has_kmod" | grep "/lib/modules/[0-9].*" | head -1)))
		ln -s "$modulesdir" /lib/modules/"$(uname -r)"
	fi
}
